apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: xscotophilic/docker-multicontainer-complex-app-client
      ports:
        - containerPort: 3000
